apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: healthcheck
  namespace: default
  labels:
    k8s-app: healthcheck
spec:
  selector:
    matchLabels:
      name: healthcheck
  template:
    metadata:
      labels:
        name: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: prashant5375/healthcheck:latest
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
